apiVersion: v1
kind: BuildConfig
metadata:
  name: slack-youtube-cmd
  labels:
    name: slack-youtube-cmd
spec:
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  source:
    type: "Binary"
  output:
    to:
      kind: ImageStreamTag
      name: slack-youtube-cmd:latest
  strategy:
    dockerStrategy: {}
    type: Docker